#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# This file is part of couchapp released under the Apache 2 license. 
# See the NOTICE for more information.

from couchapp.dispatch import run

if __name__ == '__main__':
    run()
